title: CTRA@DGSSZ
logo: /assets/img/logo.png
description: Computing Technology Research Association of Dongguan Middle School - Songshan Lake School (Group) Dongguan No.13 High School.
show_downloads: true
google_analytics:
# theme: r3kapig # use in local, don't commit this file
remote_theme: ssz-ctra/ssz-ctra.github.io # for remote
exclude: ['_site', 'node_modules', 'script', 'LICENSE', 'README.md']
